### ISSUE TITLE
[Script python] Garder les propriétés du premier post

### ISSUE THREAD

**Issue by Niks4925** [XaaT/hfr-topic-git2hfr#1]
Si on édite un premier post avec le script, le sondage éventuel et les sujets liés sont réinitialisés.
Il faudrait voir si c'est possible de les récupérer avant l'édition.

**Comment by Niks4925** [comment]
Wrong repo, il me semblait bien que j'avais déjà ouvert ce ticket...

**Comment by XaaT** [comment]
:D la drogue ;o
